### ISSUE TITLE
ValueError when trying to import *.fds file

### ISSUE THREAD

**Issue by Helllink** [firetools/blenderfds#50]
I get the following error when I import an fds file:

```
Traceback (most recent call last):
  File "C:\Users\sth\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderfds\bl\operators\scene_import.py", line 57, in execute
    utils.ui.view_all(context=context)
  File "C:\Users\sth\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderfds\utils\ui.py", line 92, in view_all
    bpy.ops.view3d.view_all(override)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported
```
I use the latest stable version of BlenderFDS and Blender 4.1.1 on Windows11.

**Comment by emanuelegissi** [comment]
Hi, this is a known issue with Blender 4.1 (
https://github.com/firetools/blenderfds/issues/47). This should only
prevent automatic zooming in imported objects, but does not affect the
correct import of the fds file.

I'm going to fix it as soon as possible.
Thank you for reporting it.
Emanuele

Il mer 26 giu 2024, 13:39 Helllink ***@***.***> ha scritto:
